# migrations/script.py.mako

"""add_ranking_antifraude_fields

Revision ID: b7b9e66c49bc
Revises: d494f82e27a9
Create Date: 2026-02-07 00:05:10.490108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = 'b7b9e66c49bc'
down_revision = 'd494f82e27a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config_restaurante', sa.Column('permitir_finalizar_fora_raio', sa.Boolean(), nullable=True))
    op.add_column('config_restaurante', sa.Column('distancia_base_motoboy_km', sa.Float(), nullable=True))
    op.add_column('entregas', sa.Column('valor_lanche', sa.Float(), nullable=True))
    op.add_column('entregas', sa.Column('valor_diaria', sa.Float(), nullable=True))
    op.add_column('entregas', sa.Column('delivery_started_at', sa.DateTime(), nullable=True))
    op.add_column('entregas', sa.Column('delivery_finished_at', sa.DateTime(), nullable=True))
    op.add_column('entregas', sa.Column('finalizado_fora_raio', sa.Boolean(), nullable=True))
    op.add_column('motoboys', sa.Column('cpf', sa.String(length=11), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motoboys', 'cpf')
    op.drop_column('entregas', 'finalizado_fora_raio')
    op.drop_column('entregas', 'delivery_finished_at')
    op.drop_column('entregas', 'delivery_started_at')
    op.drop_column('entregas', 'valor_diaria')
    op.drop_column('entregas', 'valor_lanche')
    op.drop_column('config_restaurante', 'distancia_base_motoboy_km')
    op.drop_column('config_restaurante', 'permitir_finalizar_fora_raio')
    # ### end Alembic commands ###