# migrations/script.py.mako

"""add_site_cliente_tables_fidelidade_bairros_promocoes

Revision ID: c6876da95770
Revises: 006_add_modo_prioridade
Create Date: 2026-02-03 22:58:53.216611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = 'c6876da95770'
down_revision = '006_add_modo_prioridade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_motoboys_restaurante_usuario_unique'), table_name='motoboys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_motoboys_restaurante_usuario_unique'), 'motoboys', ['restaurante_id', 'usuario'], unique=1)
    # ### end Alembic commands ###