# migrations/script.py.mako

"""add_pagamento_real_fields

Revision ID: d494f82e27a9
Revises: c6876da95770
Create Date: 2026-02-03 23:32:19.234995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = 'd494f82e27a9'
down_revision = 'c6876da95770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('forma_pagamento_real', sa.String(length=50), nullable=True))
    op.add_column('pedidos', sa.Column('valor_pago_dinheiro', sa.Float(), nullable=True))
    op.add_column('pedidos', sa.Column('valor_pago_cartao', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'valor_pago_cartao')
    op.drop_column('pedidos', 'valor_pago_dinheiro')
    op.drop_column('pedidos', 'forma_pagamento_real')
    # ### end Alembic commands ###